---
# Inherit most of the variables from CV_PATHFINDERS_TESTS

wan_route_servers:
  # Not testing the overloading
  - hostname: cv-pathfinder-pathfinder1
  - hostname: cv-pathfinder-pathfinder2
  # This one is not in the inventory pathfinder1 & 2
  - hostname: cv-pathfinder-pathfinder3
    vtep_ip: 6.6.6.6
    path_groups:
      - name: MPLS
        interfaces:
          - name: Ethernet1
            ip_address: 172.17.17.17/31
      - name: INET
        interfaces:
          - name: Ethernet2
            ip_address: 10.50.50.50/31
