hostname: autovpn-edge-no-default-policy
is_deployed: true
router_bgp:
  as: '65000'
  router_id: 192.168.30.1
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 16
  updates:
    wait_install: true
  redistribute_routes:
  - source_protocol: connected
    route_map: RM-CONN-2-BGP
  peer_groups:
  - name: WAN-OVERLAY-PEERS
    type: wan
    update_source: Dps1
    bfd: true
    password: htm4AZe9mIQOO1uiMuGgYQ==
    send_community: all
    maximum_routes: 0
    remote_as: '65000'
  address_family_evpn:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: false
  address_family_path_selection:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
    bgp:
      additional_paths:
        receive: true
        send:
          any: true
  neighbors:
  - ip_address: 2.2.2.2
    peer_group: WAN-OVERLAY-PEERS
    peer: autovpn-rr3
    description: autovpn-rr3
  vrfs:
  - name: default
    rd: 192.168.30.1:1
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '1:1'
      export:
      - address_family: evpn
        route_targets:
        - '1:1'
        - route-map RM-EVPN-EXPORT-VRF-DEFAULT
  - name: IT
    router_id: 192.168.30.1
    rd: 192.168.30.1:100
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - 100:100
      export:
      - address_family: evpn
        route_targets:
        - 100:100
    redistribute_routes:
    - source_protocol: connected
  - name: PROD
    router_id: 192.168.30.1
    rd: 192.168.30.1:42
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '42:42'
      export:
      - address_family: evpn
        route_targets:
        - '42:42'
    redistribute_routes:
    - source_protocol: connected
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
spanning_tree:
  mode: none
vrfs:
- name: MGMT
  ip_routing: false
- name: IT
  tenant: TenantA
  ip_routing: true
- name: PROD
  tenant: TenantA
  ip_routing: true
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet1
  peer_type: l3_interface
  ip_address: dhcp
  shutdown: false
  type: routed
  dhcp_client_accept_default_route: true
loopback_interfaces:
- name: Loopback0
  description: Router_ID
  shutdown: false
  ip_address: 192.168.30.1/32
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.30.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
- name: RM-EVPN-EXPORT-VRF-DEFAULT
  sequence_numbers:
  - sequence: 30
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
ip_security:
  ike_policies:
  - name: AUTOVPN-IKE
    local_id: 192.168.255.1
  sa_policies:
  - name: AUTOVPN-SA
  profiles:
  - name: AUTOVPN
    ike_policy: AUTOVPN-IKE
    sa_policy: AUTOVPN-SA
    connection: start
    shared_key: ABCDEF1234567890
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
  key_controller:
    profile: AUTOVPN
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_path_selection:
  tcp_mss_ceiling:
    ipv4_segment_size: auto
  path_groups:
  - name: INET
    id: 101
    local_interfaces:
    - name: Ethernet1
      stun:
        server_profiles:
        - INET-autovpn-rr3-Ethernet1
    dynamic_peers:
      enabled: true
    static_peers:
    - router_ip: 2.2.2.2
      name: autovpn-rr3
      ipv4_addresses:
      - 10.7.7.7
    ipsec_profile: AUTOVPN
  load_balance_policies:
  - name: LB-CONTROL-PLANE-PROFILE
    path_groups:
    - name: INET
  - name: LB-DEFAULT-AVT-POLICY-DEFAULT
    path_groups:
    - name: INET
  policies:
  - name: DEFAULT-AVT-POLICY-WITH-CP
    rules:
    - id: 10
      application_profile: CONTROL-PLANE-APPLICATION-PROFILE
      load_balance: LB-CONTROL-PLANE-PROFILE
    default_match:
      load_balance: LB-DEFAULT-AVT-POLICY-DEFAULT
  vrfs:
  - name: default
    path_selection_policy: DEFAULT-AVT-POLICY-WITH-CP
stun:
  client:
    server_profiles:
    - name: INET-autovpn-rr3-Ethernet1
      ip_address: 10.7.7.7
application_traffic_recognition:
  application_profiles:
  - name: CONTROL-PLANE-APPLICATION-PROFILE
    applications:
    - name: CONTROL-PLANE-APPLICATION
  applications:
    ipv4_applications:
    - name: CONTROL-PLANE-APPLICATION
      dest_prefix_set_name: CONTROL-PLANE-APP-DEST-PREFIXES
  field_sets:
    ipv4_prefixes:
    - name: CONTROL-PLANE-APP-DEST-PREFIXES
      prefix_values:
      - 2.2.2.2/32
dps_interfaces:
- name: Dps1
  description: DPS Interface
  ip_address: 192.168.255.1/32
vxlan_interface:
  Vxlan1:
    description: autovpn-edge-no-default-policy_VTEP
    vxlan:
      udp_port: 4789
      source_interface: Dps1
      vrfs:
      - name: default
        vni: 1
      - name: IT
        vni: 100
      - name: PROD
        vni: 42
