---
- name: "Gather SFP info to json file"
  hosts: all
  connection: local
  gather_facts: False
  ignore_errors: yes  


  vars_prompt:
    - name:   "customer"
      prompt: "Please enter customer name: (no spaces) "
      default: "Hvaler_Bredband"
      private: no

    - name:  "mailreciever"
      prompt: "Please enter mailaddress to recieve results: "
      default: "jon.bovre@netnordic.com"
      private: no


  vars:
    scriptname: sfp-info
    filedesc: sfp_info_for_
    filename: "{{scriptname}}"
    systempath: /etc/ansible/{{scriptname}}

  tasks:



  - name: ansible remove results directory
    run_once: true
    file:
      path: /"{{systempath}}/results
      state: absent

  - name: ansible create new results directory
    run_once: true
    file:
      path: "/{{systempath}}/results"
      state: directory


  - name: ensure empty file exists
    run_once: true
    copy:
      content: ""
      dest: "{{systempath}}/results/{{filename}}.json"
      force: yes
#      group: jonbov
#      owner: jonbov
      mode: 0555


  - name: get SFP info
#    hosts: ACCESS
    ce_command:
      commands:
        - display transciever verbose
#    async: 40
#    poll: 10
    retries: 3
    delay: 3
    register: sfpvar

  - local_action: lineinfile line='{{sfpvar | to_nice_json }}' insertafter=EOF dest="{{systempath}}/results/{{filename}}.json"




  - name: execute python script to create CSV file
    run_once: true
  #  command: python {{systempath}}/convert-sfp-to-csv.py
    args:
       chdir: "{{systempath}}/"



  - name: Send e-mail, attaching files
    run_once: true
    mail:
     host: mail.bovre.info
     port: 25
     username: ansible@bovre.info
     password: SentFromHvaler
     subject: Ansible - SFP report for {{customer}}
     body: Attached discovered SFP info discovered for {{customer}}
     from: ansible@bovre.info
     to:
     - <{{mailreciever}}>
     attach:
     - "{{systempath}}/results/{{filename}}.json.csv"
     - "{{systempath}}/results/{{filename}}.json"
     headers:
     - Reply-To=noreply@bovre.info
     - X-Special="Something or other"
     charset: us-ascii
    delegate_to: localhost
