---
- name: Deploy configuration files for DC1 EVPN underlay
  hosts: fabric2
  gather_facts: no
  connection: local
  pre_tasks:
    - include_vars: "{{lookup('env','PWD')}}/playbooks/authentication.yml"


  tasks:
  - name: Configure switche interfaces with hw profiles
    eos_config:
#      provider: "{{arista_credentials}}"
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_dc1_underlay_hw_speed.cfg"
  - name: Configure switches with IP adresses
    eos_config:
#      provider: "{{arista_credentials}}"
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_dc1_underlay_ip_intf.cfg"
  - name: Configure switches with MLAG
    eos_config:
#      provider: "{{arista_credentials}}"
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_dc1_underlay_mlag.cfg"
#  - name: Configure switches with ISIS
#    eos_config:
#      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_dc1_underlay_isis.cfg"
  - name: Configure switches with BGP
    eos_config:
#      provider: "{{arista_credentials}}"
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_dc1_underlay_bgp.cfg"
