


# Note: examples below use the following provider dict to handle
#       transport and authentication to the node.



---
- name: Huawei VRP command test
  hosts: access
  serial: 1
  connection: local
  gather_facts: no
  vars_files:
   - /etc/ansible/secure/vrp_passwords
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      port: "{{ ansible_ssh_port }}"
      username: "{{ vrp_username }}"
      password: "{{ vrp_password }}"
      transport: cli
    dest_dir: configs_hvaler
    template_dir: templates_ftth/hvaler

  tasks:

  - name: "Create directory"
    file:
      path: "{{ dest_dir }}"
      state: directory
    run_once: true
    delegate_to: localhost

  - name: "Create subdirectory for each host"
    file:
      path: "{{ dest_dir }}/{{ inventory_hostname }}"
      state: directory
#    run_once: true
    delegate_to: localhost


  - name: "create common configuration for VRP device"
    template:
       src={{ template_dir }}/ansible_57xx_ftth_v2.j2
       dest={{ dest_dir }}/{{ inventory_hostname }}/{{ inventory_hostname }}.cfg


