# Copyright (c) 2023-2024 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  wan_path_groups:
    description: |-
      PREVIEW: This key is currently not supported
      List of path-groups used for the WAN configuration.
    type: list
    primary_key: name
    items:
      type: dict
      keys:
        name:
          type: str
          description: Path-group name.
        id:
          type: int
          convert_types:
            - str
          description: |-
            Path-group id.

            TODO: Required until an auto ID algorithm is implemented.
          required: true
        description:
          type: str
          description: Additional information about the path-group for documentation purposes.
        ipsec:
          type: bool
          description: |-
            Flag to configure IPsec at the path-group level.

            When set to `true`, IPsec is enabled for both the static and dynamic peers.
          default: true
        import_path_groups:
          type: list
          description: List of [ath-groups to import in this path-group.
          items:
            type: dict
            keys:
              remote:
                type: str
                description: Remote path-group to import.
              local:
                type: str
                description: Optional, if not set, the path-group `name` is used as local.
