---
- hosts: nn_sros
#- hosts: 10.14.34.205
  gather_facts: true

  vars:
  #  vars_file: sros_gk15_routing.yml
    vars_file: sros_nnlab_routing.yml
    ansible_network_os: nokia.sros.light
    ansible_command_timeout: 120 # 2 minutes
    sros_dir: "/project/ansible_sros"


  tasks:

#-------------------------------------------------------------------
#   Delete all config files, reboot
#-------------------------------------------------------------------

  - name: reset device
    cli_config:
        config: | 
          file
          delete config.* force 
          exit
          /admin reboot now



