---
- hosts: 
    nn_sros
    tags_gk15_sros
  connection: network_cli
  gather_facts: No

  vars:
    vars_file: sros_nnlab_routing.yml
    ansible_network_os: nokia.sros.light
    ansible_command_timeout: 120 # 2 minutes
    sros_dir: "/project/ansible_sros"


  tasks:
#-------------------------------------------------------------------
#   Delete all config files
#-------------------------------------------------------------------

  - name: delete config files
    cli_command:
      command: file delete config.* force 

