---
- hosts: 
    nn_sros
    tags_nn_sros
    tags_gk15_sros
#- hosts: 10.14.34.205
  connection: network_cli
  gather_facts: No

  vars:
    vars_file: sros_nnlab_routing.yml
    ansible_network_os: nokia.sros.light
    ansible_command_timeout: 120 # 2 minutes
    sros_dir: "/project/ansible_sros"


  tasks:
#-------------------------------------------------------------------
#   Admin save
#-------------------------------------------------------------------


  - name: save
    cli_command:
      command: admin save
      
       
