---
- hosts: 
    nn_sros
    tags_nn_sros
    tags_gk15_sros
   #device_roles_core
   # device_roles_access
  vars:
    ansible_network_os: nokia.sros.light
  connection: ansible.netcommon.network_cli
  gather_facts: No


  tasks:
  - name: get system information
    ansible.netcommon.cli_command:
      command: show system information | match "System Name"
    register: output1

  - name: display output
    debug:
      msg: |
        {{output1.stdout}}
