---
- hosts: nn_sros
#- hosts: 10.14.34.205
  gather_facts: true

  vars:
  #  vars_file: sros_gk15_routing.yml
    vars_file: sros_nnlab_routing.yml
    ansible_network_os: nokia.sros.light
    ansible_command_timeout: 120 # 2 minutes
    sros_dir: "/project/ansible_sros"


  tasks:
#-------------------------------------------------------------------
#   Delete all config files, reboot
#-------------------------------------------------------------------
  - name: file dir (classic)
    cli_command:
      command: file dir
    register: output1

  - name: display output1
    debug:
      msg: |
        {{output1.stdout}}

  - name: reboot node (abort)
    cli_command:
      command: admin reboot
      prompt:
        - "Are you sure you want to reboot (y/n)?"
      answer:
        - 'n'
    register: output4


  - name: display output4
    debug:
      msg: |
        {{output4.stdout}}


  - name: delete config files
    cli_command:
      command: file delete config.* force 

  - name: file dir (classic)
    cli_command:
      command: file dir
    register: output1

  - name: display outputx
    debug:
      msg: |
        {{output1.stdout}}

  - name: reboot
    cli_command:
      command: admin reboot now 
       
 # - name: reset device
#    cli_config:
#        config: | 
#          file
#          delete config.* force 
#          exit
#          /admin reboot now



