---
- hosts: 
    SAR-8-200.nrslab.net
    SAR-8-201.nrslab.net
    SAR-8-203.nrslab.net
  gather_facts: no

  vars:
  #  vars_file: sros_gk15_routing.yml
    vars_file: sros_nnlab_routing.yml
    vprn_file: sros_nnlab_vprn.yml
    ansible_network_os: nokia.sros.light
    sros_dir: "/project/ansible_sros"


  tasks:
 
  - name: register base directory
    set_fact:
      base_path: "{{lookup('env','PWD')}}"


  - name: create full directory
    set_fact:
      dir_path: "{{base_path + sros_dir}}"

  - name: show full directory
    debug:
      msg: "{{ dir_path }}"
      
  - name: Create config directory
    file:
      path: "{{dir_path}}/configs"
      state: directory
#-------------------------------------------------------------------
#   Create and push G.8275.1 
#-------------------------------------------------------------------

  - name: Register variables
    include_vars:
      file: "{{dir_path}}/vars/{{vars_file}}"
      name: g8275
  #    run_once: true
  - name: Show g8275 variables
    debug:
      msg: "{{ g8275 }}"



  - name: Create g8275 configuration file
    template:
      src: "{{dir_path}}/templates/sros_G8275dot2.j2"
      dest: "{{dir_path}}/configs/{{inventory_hostname}}_g8275dot2.cfg"

  - name: Read file content
    set_fact:
        sros_configuration: "{{ lookup('file', '{{dir_path}}/configs/{{inventory_hostname}}_g8275dot2.cfg') }}"

  - name: push config to device
    cli_config:
        config: | 
          {{ sros_configuration }}
