---
- hosts: 
    #nn_sros
    10.14.34.205
  gather_facts: No

  vars:
  #  vars_file: sros_gk15_routing.yml
    vars_file: sros_nnlab_routing.yml
    ansible_network_os: nokia.sros.light
    ansible_command_timeout: 120 # 2 minutes
    sros_dir: "/project/ansible_sros"


  tasks:
 
  - name: register base directory
    set_fact:
      base_path: "{{lookup('env','PWD')}}"


  - name: create full directory
    set_fact:
      dir_path: "{{base_path + sros_dir}}"

  - name: show full directory
    debug:
      msg: "{{ dir_path }}"
  
#-------------------------------------------------------------------
#   Create config directory on runner
#-------------------------------------------------------------------
  - name: Create config directory
    file:
      config_path: "{{dir_path}}/configs"
      state: directory

  - name: show config directory
    debug:
      msg: "{{ config_path }}"


  - name: Register variables
    include_vars:
      file: "{{dir_path}}/vars/{{vars_file}}"
#      file: "{{vars_file}}"
      name: underlay
  #    run_once: true

  - name: Test all variables
    debug:
      msg: "{{ underlay }}"
  #    run_once: true


#-------------------------------------------------------------------
#   Create and push system config
#-------------------------------------------------------------------
  - name: Create system configuration file
    template:
      src: "{{dir_path}}/templates/sros_system.j2"
      dest: "{{dir_path}}/configs/{{inventory_hostname}}_system.cfg"
#      dest: "{{inventory_hostname}}_system.cfg"

 


  - name: Read system file content
    set_fact:
        system_configuration: "{{ lookup('file', '{{dir_path}}/configs/{{inventory_hostname}}_system.cfg') }}"
#        system_configuration: "{{ lookup('file', '{{inventory_hostname}}_system.cfg') }}"

  - name: push config to device
    cli_config:
        config: | 
          {{ system_configuration }}
