---
- hosts: 
    nn_sros
    tags_gk15_sros
#- hosts: 10.14.34.205
  gather_facts: No

  vars:
  #  vars_file: sros_gk15_routing.yml
    vars_file: sros_nnlab_routing.yml
    ansible_network_os: nokia.sros.light
    ansible_command_timeout: 120 # 2 minutes
    sros_dir: "/project/ansible_sros"


  tasks:
 
  - name: register base directory
    set_fact:
      base_path: "{{lookup('env','PWD')}}"


  - name: create full directory
    set_fact:
      dir_path: "{{base_path + sros_dir}}"

  - name: show full directory
    debug:
      msg: "{{ dir_path }}"
  
#-------------------------------------------------------------------
#   Create config directory on runner
#-------------------------------------------------------------------
  - name: Create config directory
    file:
      path: "{{dir_path}}/configs"
      state: directory

  - name: Register variables
    include_vars:
      file: "{{dir_path}}/vars/{{vars_file}}"
#      file: "{{vars_file}}"
      name: underlay
  #    run_once: true

  - name: Test all variables
    debug:
      msg: "{{ underlay }}"
  #    run_once: true


#-------------------------------------------------------------------
#   Create and push base router config
#-------------------------------------------------------------------

  - name: Create router underlay configuration file
    template:
      src: "{{dir_path}}/templates/sros_underlay.j2"
      dest: "{{dir_path}}/configs/{{inventory_hostname}}_router.cfg"

  - name: Read router file content
    set_fact:
        port_configuration: "{{ lookup('file', '{{dir_path}}/configs/{{inventory_hostname}}_router.cfg') }}"

  - name: push config to device
    cli_config:
        config: | 
          {{ port_configuration }}
