---
- hosts: 
    10.14.34.208 
    10.14.34.209
  gather_facts: no

  vars:
  #  vars_file: sros_gk15_routing.yml
    vars_file: sros_nnlab_routing.yml
    vprn_file: sros_nnlab_vprn.yml
    ansible_network_os: nokia.sros.light
    sros_dir: "/project/ansible_sros"


  tasks:
 
  - name: register base directory
    set_fact:
      base_path: "{{lookup('env','PWD')}}"


  - name: create full directory
    set_fact:
      dir_path: "{{base_path + sros_dir}}"

  - name: show full directory
    debug:
      msg: "{{ dir_path }}"
      
  - name: Create config directory
    file:
      path: "{{dir_path}}/configs"
      state: directory
#-------------------------------------------------------------------
#   Create and push VPRN router config
#-------------------------------------------------------------------

  - name: Register VPRN variables
    include_vars:
      file: "{{dir_path}}/vars/{{vprn_file}}"
      name: vprn
  #    run_once: true
  - name: Show VPRN variables
    debug:
      msg: "{{ vprn }}"



  - name: Create VPRN configuration file
    template:
      src: "{{dir_path}}/templates/sros_vprn_create.j2"
      dest: "{{dir_path}}/configs/{{inventory_hostname}}_vprn_create.cfg"

  - name: Read VPRN file content
    set_fact:
        vprn_configuration: "{{ lookup('file', '{{dir_path}}/configs/{{inventory_hostname}}_vprn_create.cfg') }}"

  - name: push VPRN config to device
    cli_config:
        config: | 
          {{ vprn_configuration }}
