---
- hosts: sros
  gather_facts: no

  vars:
  #  vars_file: sros_gk15_routing.yml
    vars_file: sros_nnlab_routing.yml
    ansible_network_os: nokia.sros.light
  
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/{{vars_file}}"
      name: underlay
  #    run_once: true
  - name: Test all variables
    debug:
      msg: "{{ underlay }}"
  #    run_once: true
  - name: Create configuration file for system
    template:
      src: "{{lookup('env','PWD')}}/templates/sros_system.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_system.cfg"
  - name: Create router underlay configuration file
    template:
      src: "{{lookup('env','PWD')}}/templates/sros_underlay.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_router.cfg"
  - name: Create configuration file for MDA
    template:
      src: "{{lookup('env','PWD')}}/templates/sros_mda.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_mda.cfg"
  - name: Create configuration file for ports
    template:
      src: "{{lookup('env','PWD')}}/templates/sros_port.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_port.cfg"

  - name: Read the file
    file:
      path: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_system.cfg"
      dest: "{{lookup('env','PWD')}"
      register: sysfile
      
  - name: print file
    debug:
      msg: “{{ sysfile.content }}”
  
  - name: read system config
    template:
      file_content: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_system.cfg"
      debug:
        msg: "The content of the file is: {{ file_content }}"

      debug:
        msg: "The content of the file is: {{ file_content }}"
  - name: push system config
    cli_config:
      config: | 
        {{ file_content }}
