---
- hosts: sros
  vars:
    ansible_network_os: nokia.sros.light
#  vars_prompt:
#    - name: admin
#      prompt: "Username"
#      private: no
#    - name: admin
#      prompt: "Password"
#  connection: network_cli
  gather_facts: No
  #vars:
  #  vars_file: sros_gk15_routing.yml
  #  vars_file: sros_nnlab_routing.yml

  collections:
  - nokia.sros

  tasks:
  - name: save config
    cli_config:
      config: |
        exit all
        admin save
        

  - name: backup
    cli_config:
      backup: yes
      backup_options:
        filename: "{{ inventory_hostname }}.cfg"
        dir_path: /tmp