---
- hosts: all
  gather_facts: no
  
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/sros_underlay.yml"
      name: underlay
  - name: Test all variables
    debug:
      msg: "{{ underlay }}"
  - name: Create a configuration file
    template:
      src: "{{lookup('env','PWD')}}/templates/sros_underlay.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_router.cfg"
      
      
