---
- hosts: all
  gather_facts: no
  
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/sros_underlay.yml"
      name: underlay
  - name: Test all variables
    debug:
      msg: "{{ underlay }}"
  - name: Create configuration file for system
    template:
      src: "{{lookup('env','PWD')}}/templates/sros_system.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_system.cfg"
  - name: Create router underlay configuration file
    template:
      src: "{{lookup('env','PWD')}}/templates/sros_underlay.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_router.cfg"
  - name: Create configuration file for MDA
    template:
      src: "{{lookup('env','PWD')}}/templates/sros_mda.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_mda.cfg"
      
