---
- hosts: 10.0.10.236
  gather_facts: no
  connection: ansible.netcommon.network_cli ansible_user=admin ansible_password=admin 
  
  tasks:
  - name: push config
    ansible.netcommon.cli_command:
      command:
        - show system time
    register: sys_vars

  - name: Debug
    debug:
      vars: sys_vars