---

  - name: Test VRP connection
    hosts: vrp

    connection: local
    gather_facts: no
    ignore_errors: yes
    vars:
      cli:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        

    tasks:
    - name: "Config top level and save"
      ce_config:
        lines: sysname {{ inventory_hostname }}
        save: yes
        provider: "{{ cli }}"           

    - name: "config ACL 2600"
      ce_config:
        lines: acl 2600
        save: yes
      
    - name: "config"
      ce_config:
        lines: sysname test
        
    - name: "Config ACL"
      ce_config:
        lines:
          - rule 10 permit source 1.1.1.1 0
        parents: acl 2000
        before: undo acl 2000
        match: exact
        
    - name: "Config domain"
      ce_config:
        lines:
          - domain test_ansible
        parents: aaa
        match: exact
        
    - name: "Config ACL 2500"
      ce_config:
        lines: ACL 2500
        save: yes
        provider: "{{ cli }}"       
