
---
- name: "CE test"
  hosts: all
  connection: local
  gather_facts: False
  ignore_errors: yes
  
#  vars:
#    result []

  tasks:

#  - name: "Clean file version2.log"
#      file: path:/home/jonbov/version2.log state=empty

  - name: Get Version info
    ce_command:
      commands: 
        - display current | in sysname
        - display version
    register: version    
  - debug:        msg="{{ version }}"
#  - local_action: copy content='{{ version | to_nice_json }}' dest="/home/jonbov/version.log"
#  - local_action: lineinfile line='{{ version | to_nice_json }}' insertafter=EOF dest="/home/jonbov/version2.log"
  - local_action: copy content='{{ version | to_nice_json }}' dest="/home/jonbov/version_{{ inventory_hostname }}.log"



  - name: run display commands
    ce_command:
      commands:
        - display current | in sysname
        - display lldp neighbor brief
    register: lldp

  - debug:        msg="{{lldp | to_nice_json}}"
#  - local_action: copy content='{{lldp | to_nice_json}}' dest="/home/jonbov/result.log"
#  - local_action: lineinfile line='{{lldp | to_nice_json }}' insertafter=EOF dest="/home/jonbov/result.log"
  - local_action: copy content='{{ lldp | to_nice_json }}' dest="/home/jonbov/LLDP_{{ inventory_hostname }}.log"           

  - name: Removing existing lldp.log
    file:
      path: /home/jonbov/lldp.log
      state: absent

  - name: ensure file exists
    copy:
      content: ""
      dest: /home/jonbov/lldp.log
      force: no
#      group: sys
      owner: jonbov
      mode: 0555


  - name: get LLDP info
#    raw: display lldp neighbor brief
    ce_command:
      commands:
        - display current | in sysname
        - display lldp neighbor brief
    register: lldp2

  - debug:        msg="{{lldp2 | to_nice_json}}"
#  - local_action: copy content='{{lldp2 | to_nice_json}}' dest="/home/jonbov/lldp.log"
  - local_action: lineinfile line='{{lldp2 | to_nice_json }}' insertafter=EOF dest="/home/jonbov/lldp.log"
#  - local_action: copy content='{{ lldp2 | to_nice_json }}' dest="/home/jonbov/LLDP_{{ inventory_hostname }}.log"
