---
- hosts: all
  gather_facts: no
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/underlay_dc1.yml"
      name: underlay
  - name: Test all variables
    debug:
      msg: "{{ underlay }}"
  - name: Test spesific variable
    debug:
      msg: "{{ underlay['7010-1.nrslab.eu']['isis']['system_id'] }}"
  - name: Create a configuration file
    template:
      src: "{{lookup('env','PWD')}}/templates/underlay.j2"
      dest: "{{lookup('env','PWD')}}/configs/interface_{{inventory_hostname}}_underlay.cfg"
      
