---
- hosts: sros
  gather_facts: no

  vars:
  #  vars_file: sros_gk15_routing.yml
    vars_file: sros_nnlab_routing.yml
    ansible_network_os: nokia.sros.light
  
  tasks:
  - name: register base directory
    set_fact:
      dir_path: "{{lookup('env','PWD')}}"
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/{{vars_file}}"
      name: underlay
  #    run_once: true
  - name: Test all variables
    debug:
      msg: "{{ underlay }}"
  #    run_once: true
#-------------------------------------------------------------------
#   Create system config
#-------------------------------------------------------------------
  - name: Create system configuration file
    template:
      src: "{{lookup('env','PWD')}}/templates/sros_system.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_system.cfg"

 # - name: Read system file content
 #   set_fact:
 #       configuration: "{{ lookup('file', '/home/jonbov/ansible_sros/configs/{{inventory_hostname}}_system.cfg') }}"
  - name: Read system file content
    set_fact:
        system_configuration: "{{ lookup('file', '{{dir_path}}/configs/{{inventory_hostname}}_system.cfg') }}"

  - name: push config to device
    cli_config:
        config: | 
          {{ system_configuration }}

#-------------------------------------------------------------------
#   Create MDA and port config
#-------------------------------------------------------------------

  - name: Create configuration file for MDA
    template:
      src: "{{dir_path}}/templates/sros_mda.j2"
      dest: "{{dir_path}}/configs/{{inventory_hostname}}_mda.cfg"


  - name: Read MDA file content
    set_fact:
        mda_configuration: "{{ lookup('file', '{{dir_path}}/configs/{{inventory_hostname}}_mda.cfg') }}"

  - name: push config to device
    cli_config:
        config: | 
          {{ mda_configuration }}
