---
- name: Deploy configuration files for DC1 EVPN underlay
  hosts: leaf7.bovre.net
  gather_facts: no
  connection: local
  pre_tasks:
    - include_vars: "{{lookup('env','PWD')}}/playbooks/authentication.yml"


  tasks:
  - name: Configure switches with IP adresses
    eos_config:
#      provider: "{{arista_credentials}}"
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_dc1_underlay_ip_intf.cfg"
  - name: Configure switche interfaces with hw profiles
    eos_config:
#      provider: "{{arista_credentials}}"
# https://stackoverflow.com/questions/59999716/how-to-pass-input-to-interactive-command-using-ansible
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/expect_module.html
    expect:
      command: abc_1.2_udate.bin /tmp/log
      responses:
        'Do you want to proceed y/n?': "y"
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_dc1_underlay_hw_speed.cfg"

