---
- name: Deploy configuration files for DC1 EVPN underlay
  hosts: spine2.bovre.net
  gather_facts: no
  connection: local
  pre_tasks:
    - include_vars: "{{lookup('env','PWD')}}/playbooks/authentication.yml"


  tasks:
  - name: Configure switches with IP adresses
    eos_config:
#      provider: "{{arista_credentials}}"
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_dc1_underlay_ip_intf.cfg"
  - name: Configure switche interfaces with hw profiles
    eos_config:
#      provider: "{{arista_credentials}}"
# https://stackoverflow.com/questions/59999716/how-to-pass-input-to-interactive-command-using-ansible
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/expect_module.html
      #Spine2(config)#hardware port-group 1 select Et1-4 
      #! 
      #                  WARNING!
      #   Changing the port-group mode will cause all
      #   interfaces on the switch to flap.
      #   
      #Do you wish to proceed with this command? [y/N]y
      #Spine2(config)#
      expect:
        command: hardware port-group 1 select Et1-4 
        responses:
          'Do you wish to proceed with this command? [y/N]': "y"
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_dc1_underlay_hw_speed.cfg"

