---
- name: Configure Nokia SR OS device
  hosts: sar-8
  gather_facts: no
#  connection: network_cli
  collections:
  - nokia.sros

  tasks:
#    - name: Configure system name
#      ansible.netcommon.cli_config:
#        config: |
#          system
#          name SR-OS-Router

#    - name: Configure an interface
#      ansible.netcommon.cli_config:
#        config: |
#          interface "ethernet-1/1"
#          description "Uplink Interface"
#          address 192.168.1.1/24
#          no shutdown
  - name: run show version on remote devices
    ansible.netcommon.cli_command:
      command: show version

  - name: Information
    ansible.netcommon.cli_command:
      command: show system Information

  - name: Save configuration
    ansible.netcommon.cli_command:
      command: admin save
