---
- name: Deploy configuration files for DC1 EVPN underlay
  hosts: fabric2
  gather_facts: no
  connection: local
  pre_tasks:
    - include_vars: "{{lookup('env','PWD')}}/playbooks/authentication.yml"


  tasks:
  - name: Configure switche interfaces with hw profiles
    eos_config:
#      provider: "{{arista_credentials}}"
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_dc1_underlay_hw_speed.cfg"
