---
  - hosts: all
    tasks:
    - name: Add User
      eos_user:
        name: automator
        nopassword: yes
        privilege: 15
        role: network-admin
        state: present
    - name: Add SSH key
      eos_user:
        name: automator
        sshkey: "{{ lookup('file', '~/ssh/ssh_key.pub') }}"
        state: present
