---
- hosts: all
  gather_facts: no
  tasks:
  - name: Create template
    template:
      src: "{{lookup('env','PWD')}}/templates/no_vlans.j2"
      dest: "{{lookup('env','PWD')}}/configs/no_vlans_{{inventory_hostname}}.cfg"
  - name: Upload config
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/no_vlans_{{inventory_hostname}}.cfg"
