---
- name: Generate configurations for DC1 EVPN underlay
  hosts: all
  gather_facts: no
  connection: local
  pre_tasks:
    - include_vars: "authentication.yml"

  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/underlay_dc1.yml"
      name: underlay
  - name: Test all variables
    debug:
      msg: "{{ underlay }}"
  - name: Create configuration profiles for interfaces
    template:
      src: "{{lookup('env','PWD')}}/templates/underlay_interface_hw_speed.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_dc1_underlay_hw_speed.cfg"
  - name: Create configuration files for MLAG
      template:
      src: "{{lookup('env','PWD')}}/templates/underlay_mlag.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_dc1_underlay_mlag.cfg"
  - name: Create configuration files for IP interfaces
    template:
      src: "{{lookup('env','PWD')}}/templates/underlay_ip_interfaces.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_dc1_underlay_ip_intf.cfg"
  - name: Create configuration files for ISIS
    template:
      src: "{{lookup('env','PWD')}}/templates/underlay_isis.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_dc1_underlay_isis.cfg"
  - name: Create configuration files for BGP
    template:
      src: "{{lookup('env','PWD')}}/templates/underlay_bgp.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_dc1_underlay_bgp.cfg"

