---
- hosts: all
  gather_facts: no
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/underlay_dc1.yml"
      name: underlay
  - name: Test all variables
    debug:
      msg: "{{ underlay }}"
  - name: Test spesific variable
    debug:
      msg: "{{ underlay['leaf1-dc1.bovre.net']['isis']['system_id'] }}"
  - name: Create configuration files
    template:
      src: "{{lookup('env','PWD')}}/templates/isis_underlay.j2"
      dest: "{{lookup('env','PWD')}}/configs/isis_underlay_{{inventory_hostname}}.cfg"