---
- hosts: leaf1-dc1.bovre.net, spine1-dc1.bovre.net
  gather_facts: no
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/test.yml"
      name: underlay
  - name: Test all variables
    debug:
      msg: "{{ underlay }}"
