---
# Ansible Builder Execution Environment
# https://ansible.readthedocs.io/projects/builder/en/latest/definition/#version-3-sample-file
# https://www.youtube.com/watch?v=AklfCYT5aTg&list=PLOocymQm7YWbJR8BPeoWFpzx9O4vRGuHk&index=3
# modified fro SROS

version: 3

#build_arg_defaults:
#  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-certs'
#
#  EE_BUILDER_IMAGE: 'quay.io/ansible/ansible-builder:latest'

images:
  base_image:
    name: 'quay.io/ansible/awx-ee:latest'


dependencies:
  #ansible_core:
  #  package_pip: ansible-core==2.14.4
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
  python_interpreter:
    package_system: python3
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
#additional_build_step:
#  prepend:
#  prepend: 1
#    RUN dnf upgrade -y
#    RUN pip3 install --upgrade pip setuptools
#  append:
#    ENV jonbov_prod_version=1.0
#    ENV ANSIBLE_CONFIG=/runner/ansible.cfg